### ISSUE TITLE
BUG: Sutvarkyti Kurso vaizdą

### ISSUE THREAD

**Issue by Boomerius** [marijuss/ERS-admin#23]
#### I. Pašalinti kažkokį defaultinį tekstą, kurį uždeda po nuotrauka 
va tekstas: 
"Facilisis odio, dapibus ac justo acilisis gestinas."
va foto pvz:
![image](https://cloud.githubusercontent.com/assets/2337166/9037346/fe767a3e-39f2-11e5-85a2-b6bc4a975c74.png)

#### II. Pasalinti kurso pavadinima virs foto:
Čia sudvigubinta informacija.
![image](https://cloud.githubusercontent.com/assets/2337166/9038162/f4b0fac6-39fa-11e5-8811-5babb523bcb3.png)

**Comment by ErikasPetkus** [comment]
Sutvarkyta ir atnaujinta.
