### ISSUE TITLE
Widget LITE

### ISSUE THREAD

**Issue by Boomerius** [marijuss/ERS-admin#24]
Sumažintas Widgetas:
- be foto
- be grafiko (nera schedule)

Widgete matoma tik esminė informacija, (pvz nereikia grafiko, ir foto) 
Klausimas - ar galima toki widgeta padaryti?

Kadangi widgetas bus siauras ir aukštas, tai ar galima padaryti taip :
a) arba kad registarcija vyktu, didesniame lange
b) arba vesti pas mus i puslapi ir ten užbaigti registracijos procesą

![widget lite_1 1](https://cloud.githubusercontent.com/assets/2337166/9062037/65ad12dc-3ac8-11e5-85fd-111fa972bc87.png)

**Comment by ErikasPetkus** [comment]
Padaryta. parašytas javascriptas kuris atidaro tabą naujame lange + atidaro iškart modal formą.
